minmax_element
0xPwner/manos pull request #1
Opened 2021-05-06 18:35 UTC by fndrd1d1

2021-05-10 16:52 UTC, 0xPwner commented on algorithms/minmax_element.cpp
> +int main(int argc, char **argv)
I think we should have only one main that is located in project root which will execute all the tests in the future. 
So adding tests can be easy

2021-05-10 16:57 UTC, 0xPwner requested changes
nice manos

2021-05-10 16:57 UTC, kafteji commented on algorithms/minmax_element.cpp
> +            ++first;
first += 2;

2021-05-10 16:57 UTC, kafteji commented on algorithms/minmax_element.cpp
> +int main(int argc, char **argv)
I think we should have only one main that is located in project root which will execute all the tests in the future.
So adding tests can be easy.

2021-05-10 16:57 UTC, kafteji commented on algorithms/minmax_element.cpp
> +        return {min, max};
i would use std::make_pair(min, max)

2021-05-10 16:57 UTC, kafteji commented on algorithms/minmax_element.cpp
> +            return {last, last};
std::make_pair(last, last)

2021-05-19 19:00 UTC, fndrd1d1 commented on algorithms/minmax_element.cpp
> +            ++first;
✅

2021-05-19 19:01 UTC, fndrd1d1 commented on algorithms/minmax_element.cpp
> +int main(int argc, char **argv)
✅

2021-05-19 19:01 UTC, fndrd1d1 commented on algorithms/minmax_element.cpp
> +        return {min, max};
✅

2021-05-19 19:01 UTC, fndrd1d1 commented on algorithms/minmax_element.cpp
> +            return {last, last};
✅

2021-05-19 20:18 UTC, 0xPwner approved these changes
LGTM

2021-05-19 20:18 UTC, merged